#!/bin/sh
export CLASSPATH=.:lib/jts-1.4.0.jar:lib/jump.jar:lib/xercesImpl.jar:lib/Chart2D.jar:lib/Jama-1.0.1.jar:lib/jdom.jar
echo CLASSPATH: $CLASSPATH

javadoc                                                      \
     -sourcepath ./                                          \
    -overview ./overview.html                                \
    -d ./javadoc			                     \
    -use                                                     \
    -author                                                  \
    -breakiterator                                           \
    -noqualifier                                             \
    -version                                                 \
    -splitIndex                                              \
    -tag todo:a:"To Do:"                                     \
    -link http://www.vividsolutions.com/jts/javadoc          \
    -link http://www.vividsolutions.com/jcs/javadoc          \
    -windowtitle 'JUMP v1.1.0 API Specification'             \
    -doctitle 'JUMP v1.1.0 API Specification'                \
    -header '<b>JUMP</b><br><font size="-1">v1.1.0</font>'   \
    -bottom '<font size="-1"><a href="http://www.vividsolutions.com/">
            Vivid Solutions, Inc.</a><BR>
            Copyright 1999-2003 Vivid Solutions, Inc. <br>
           Victoria, British Columbia, Canada. All Rights Reserved.</font>' \
    -J-Xmx180m                                               \
    -subpackages com.vividsolutions.jump com.vividsolutions.wms 
